# Eastward wind dataframe generation

In [1]:
import pandas as pd
import numpy as np

In [2]:
lat= pd.read_csv('latitude.csv')
lat.head()

Empty DataFrame
Columns: [-89.9375, -89.8125, -89.6875, -89.5625, -89.4375, -89.3125, -89.1875, -89.0625, -88.9375, -88.8125, -88.6875, -88.5625, -88.4375, -88.3125, -88.1875, -88.0625, -87.9375, -87.8125, -87.6875, -87.5625, -87.4375, -87.3125, -87.1875, -87.0625, -86.9375, -86.8125, -86.6875, -86.5625, -86.4375, -86.3125, -86.1875, -86.0625, -85.9375, -85.8125, -85.6875, -85.5625, -85.4375, -85.3125, -85.1875, -85.0625, -84.9375, -84.8125, -84.6875, -84.5625, -84.4375, -84.3125, -84.1875, -84.0625, -83.9375, -83.8125, -83.6875, -83.5625, -83.4375, -83.3125, -83.1875, -83.0625, -82.9375, -82.8125, -82.6875, -82.5625, -82.4375, -82.3125, -82.1875, -82.0625, -81.9375, -81.8125, -81.6875, -81.5625, -81.4375, -81.3125, -81.1875, -81.0625, -80.9375, -80.8125, -80.6875, -80.5625, -80.4375, -80.3125, -80.1875, -80.0625, -79.9375, -79.8125, -79.6875, -79.5625, -79.4375, -79.3125, -79.1875, -79.0625, -78.9375, -78.8125, -78.6875, -78.5625, -78.4375, -78.3125, -78.1875, -78.0625, -77.9375, -77.8125, -77.6875, -77.5625, ...]
Index: []

[0 rows x 1440 columns]

In [3]:
lon= pd.read_csv('lon.csv')
lon.head()

Empty DataFrame
Columns: [0.0625, 0.1875, 0.3125, 0.4375, 0.5625, 0.6875, 0.8125, 0.9375, 1.0625, 1.1875, 1.3125, 1.4375, 1.5625, 1.6875, 1.8125, 1.9375, 2.0625, 2.1875, 2.3125, 2.4375, 2.5625, 2.6875, 2.8125, 2.9375, 3.0625, 3.1875, 3.3125, 3.4375, 3.5625, 3.6875, 3.8125, 3.9375, 4.0625, 4.1875, 4.3125, 4.4375, 4.5625, 4.6875, 4.8125, 4.9375, 5.0625, 5.1875, 5.3125, 5.4375, 5.5625, 5.6875, 5.8125, 5.9375, 6.0625, 6.1875, 6.3125, 6.4375, 6.5625, 6.6875, 6.8125, 6.9375, 7.0625, 7.1875, 7.3125, 7.4375, 7.5625, 7.6875, 7.8125, 7.9375, 8.0625, 8.1875, 8.3125, 8.4375, 8.5625, 8.6875, 8.8125, 8.9375, 9.0625, 9.1875, 9.3125, 9.4375, 9.5625, 9.6875, 9.8125, 9.9375, 10.0625, 10.1875, 10.3125, 10.4375, 10.5625, 10.6875, 10.8125, 10.9375, 11.0625, 11.1875, 11.3125, 11.4375, 11.5625, 11.6875, 11.8125, 11.9375, 12.0625, 12.1875, 12.3125, 12.4375, ...]
Index: []

[0 rows x 2880 columns]

In [4]:
u= pd.read_csv('eastward_wind.csv',header=None)
u.head()

,0,1,2,3,4,5,6,7,8,9,...,2870,2871,2872,2873,2874,2875,2876,2877,2878,2879
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
u.describe()

,0,1,2,3,4,5,6,7,8,9,...,2870,2871,2872,2873,2874,2875,2876,2877,2878,2879
count,485.000000,490.000000,490.000000,497.000000,503.000000,503.000000,508.000000,509.000000,508.000000,508.000000,...,458.000000,462.000000,462.000000,465.000000,467.000000,470.000000,472.000000,474.000000,472.000000,482.000000
mean,0.802082,0.657776,0.503673,0.418310,0.291829,0.179145,0.111398,-0.006483,-0.022343,-0.058327,...,2.189017,1.988398,1.787662,1.645204,1.462891,1.245149,1.129555,1.041477,0.932987,0.858029
std,6.563605,6.526625,6.518566,6.489561,6.394676,6.343027,6.282892,6.232288,6.208197,6.228060,...,7.291501,7.205790,7.162836,7.017096,6.933779,6.813383,6.744058,6.704035,6.611571,6.571100
min,-13.270000,-13.480000,-13.620000,-13.730000,-13.830000,-14.040000,-14.130000,-14.150000,-14.210000,-14.220000,...,-12.320000,-12.350000,-12.410000,-12.520000,-12.650000,-12.720000,-12.880000,-13.050000,-13.120000,-13.210000
25%,-4.710000,-4.820000,-4.920000,-5.020000,-4.930000,-4.715000,-4.632500,-4.750000,-4.762500,-4.735000,...,-4.530000,-4.590000,-4.647500,-4.660000,-4.590000,-4.777500,-4.735000,-4.722500,-4.762500,-4.637500
50%,0.960000,0.615000,-0.180000,-0.220000,-0.570000,-1.610000,-1.685000,-2.210000,-2.065000,-2.400000,...,4.015000,3.940000,3.890000,3.780000,3.610000,3.235000,2.535000,2.570000,1.915000,1.130000
75%,6.560000,6.477500,6.447500,6.250000,6.160000,6.185000,6.147500,6.220000,6.180000,6.182500,...,7.820000,7.567500,7.325000,7.140000,6.985000,6.740000,6.652500,6.545000,6.500000,6.595000
max,18.600000,16.820000,16.380000,15.830000,13.890000,13.600000,13.410000,12.330000,11.780000,11.380000,...,22.140000,22.080000,22.030000,22.030000,21.930000,21.210000,21.130000,20.960000,19.640000,19.120000

In [6]:
v= pd.read_csv('northward_wind.csv',header=None)
v.head()

,0,1,2,3,4,5,6,7,8,9,...,2870,2871,2872,2873,2874,2875,2876,2877,2878,2879
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [7]:
v.describe()

,0,1,2,3,4,5,6,7,8,9,...,2870,2871,2872,2873,2874,2875,2876,2877,2878,2879
count,485.000000,490.000000,490.000000,497.00000,503.000000,503.000000,508.000000,509.000000,508.000000,508.000000,...,458.000000,462.000000,462.000000,465.000000,467.000000,470.000000,472.000000,474.000000,472.000000,482.000000
mean,1.161485,1.216714,1.297347,1.35330,1.488310,1.646342,1.795610,1.933458,2.133898,2.352913,...,0.422445,0.497273,0.566320,0.636043,0.698630,0.775064,0.785869,0.918207,1.058136,1.108693
std,4.624219,4.665737,4.697468,4.68011,4.695401,4.718921,4.715923,4.655549,4.584063,4.518010,...,3.910998,3.965475,3.989203,4.054604,4.136276,4.221035,4.318285,4.378493,4.472500,4.563819
min,-7.960000,-7.960000,-7.750000,-7.51000,-7.200000,-7.150000,-9.620000,-8.870000,-8.100000,-7.330000,...,-8.320000,-7.510000,-7.190000,-7.020000,-6.920000,-6.950000,-7.110000,-7.200000,-7.140000,-7.660000
25%,-3.410000,-3.355000,-3.435000,-3.43000,-3.235000,-3.185000,-2.597500,-2.080000,-1.442500,-0.737500,...,-2.735000,-2.817500,-2.920000,-3.000000,-3.200000,-3.377500,-3.390000,-3.292500,-3.337500,-3.407500
50%,1.910000,1.910000,1.870000,1.87000,2.010000,2.050000,2.235000,2.440000,2.700000,2.915000,...,0.270000,0.475000,0.780000,1.070000,1.140000,1.265000,1.230000,1.580000,1.780000,1.895000
75%,4.810000,4.837500,4.840000,4.89000,5.130000,5.355000,5.472500,5.520000,5.522500,5.695000,...,3.222500,3.417500,3.392500,3.530000,3.675000,4.075000,4.205000,4.452500,4.535000,4.702500
max,11.390000,11.520000,11.690000,11.76000,11.830000,12.070000,12.240000,12.370000,12.460000,12.600000,...,10.340000,10.620000,11.010000,10.930000,10.870000,10.830000,10.760000,10.600000,10.950000,11.300000

In [8]:
# Importation des modules standards
import pandas as pd
import numpy as np 

# Importation des fonctions dont l'on se servira pour toutes les figures
from bokeh.plotting import figure, output_notebook, show

# Précision de l'affichage des graphiques dans des cellules jupyter
output_notebook()

In [33]:
import folium
m = folium.Map(location=[41, 6], zoom_start=7, tiles="Stamen Terrain")
m

In [13]:

k=6378137
lonk=(lon-180) * (k * np.pi/180.0)
latk=lat * (k * np.pi/180.0)

In [15]:
latk

Empty DataFrame
Columns: [-89.9375, -89.8125, -89.6875, -89.5625, -89.4375, -89.3125, -89.1875, -89.0625, -88.9375, -88.8125, -88.6875, -88.5625, -88.4375, -88.3125, -88.1875, -88.0625, -87.9375, -87.8125, -87.6875, -87.5625, -87.4375, -87.3125, -87.1875, -87.0625, -86.9375, -86.8125, -86.6875, -86.5625, -86.4375, -86.3125, -86.1875, -86.0625, -85.9375, -85.8125, -85.6875, -85.5625, -85.4375, -85.3125, -85.1875, -85.0625, -84.9375, -84.8125, -84.6875, -84.5625, -84.4375, -84.3125, -84.1875, -84.0625, -83.9375, -83.8125, -83.6875, -83.5625, -83.4375, -83.3125, -83.1875, -83.0625, -82.9375, -82.8125, -82.6875, -82.5625, -82.4375, -82.3125, -82.1875, -82.0625, -81.9375, -81.8125, -81.6875, -81.5625, -81.4375, -81.3125, -81.1875, -81.0625, -80.9375, -80.8125, -80.6875, -80.5625, -80.4375, -80.3125, -80.1875, -80.0625, -79.9375, -79.8125, -79.6875, -79.5625, -79.4375, -79.3125, -79.1875, -79.0625, -78.9375, -78.8125, -78.6875, -78.5625, -78.4375, -78.3125, -78.1875, -78.0625, -77.9375, -77.8125, -77.6875, -77.5625, ...]
Index: []

[0 rows x 1440 columns]

lonk=lon*2
lonk